// Brand JSON asset paths generated by `npm run build:colors`
const BRAND_ASSETS = [
    '/colors/Benjamin_Moore.json',
    '/colors/Sherwin_Williams.json',
]

export interface BrandAsset {
    brand: string;
    retrievalDate: string;
    collections: CollectionAsset[];
}

export interface CollectionAsset {
    collection: string;
    swatches: SwatchAsset[];
}

export interface SwatchAsset {
    id: string;
    name: string;
    rgb: [number, number, number];
    oklab: [number, number, number];
    oklch: [number, number, number];
}

export interface Swatch {
    id: string;
    brand: string;
    collection: string;
    name: string;
    rgb: [number, number, number];
    oklab: [number, number, number];
    oklch: [number, number, number];
}

function flattenAssetSwatches(asset: BrandAsset): Swatch[] {
    return asset.collections.flatMap(collection =>
        collection.swatches.map(swatch => ({
            ...swatch,
            brand: asset.brand,
            collection: collection.collection
        }))
    )
}

export async function loadBuiltInSwatchs(): Promise<Swatch[]> {
    const results = await Promise.allSettled(
        BRAND_ASSETS.map(url =>
            fetch(url).then(res => {
                if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
                return res.json() as Promise<BrandAsset>
            })
        )
    )
    return results.flatMap(r => (r.status === 'fulfilled' ? flattenAssetSwatches(r.value) : []))
}
